### ISSUE TITLE
Can you provide example for nuxtjs3 ?

### ISSUE THREAD

**Issue by duccanhole** [williampsena/nuxt-phaser#18]
As title, I want implement phaser into nuxtjs3 project.

**Comment by duccanhole** [comment]
thanks for response

**Comment by williampsena** [comment]
@duccanhole This plugin has been updated to support Nuxt3 and can now be used as a vue-plugin.

Live example here: https://nuxtjs-phaser.surge.sh/ 
Project example here: https://github.com/williampsena/nuxt-phaser-example

**Comment by williampsena** [comment]
The plugin is compatible with Vue 3 powered by Vite.
I made a small sample.

https://github.com/williampsena/vue-phaser-example

**Comment by williampsena** [comment]
I published an article about [plugin](https://willsena.dev/creating-amazing-games-using-phaser-and-vue-nuxt-vite)
